# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68b1a72369e983281e211a749ab6fa78e78d405b0f54b9534618034a4ea062632c990bac402d887f3ee16a40044fb81ef072e49041bf6f829de87096f8716972

test:
  secret_key_base: b0bf64edc366899bade599198bf797eaf99c36c8c13e24c35912aef608e7c6946fc6baef738a1084012d3fc359db82f95c98086bbdf7b5a668ac4e1c933b7184

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
